# The URL the site will be built for
base_url = "https://shiosaii.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Global Theme
theme = "anemone"

# Define the containers for metadata in the pluses
taxonomies = [
	{name = "categories", feed = true},
	{name = "tags", feed = true},
]

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here

# Put links in headers
header_nav = [
	{ url = "/", name_en = "/home/" },
	{ url = "/archive", name_en = "/archive/" },
]

# Ensure recent posts show up on the homepage
list_pages = true
display_author = true
author = "shiosaii"
